"""Fast, validated solvers for inertial microcavitation rheometry."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

try:
  __version__ = version("pyimr")
except PackageNotFoundError:  # a source tree that was never installed
  __version__ = "0.0.0+unknown"


__all__ = [
  "ArrudaBoyce",
  "Bingham",
  "C8",
  "CarreauYasuda",
  "CarreauZener",
  "CollapseInitialization",
  "CollapseStats",
  "Cross",
  "DYNAMICS",
  "ElasticModel",
  "Fung",
  "Gent",
  "Giesekus",
  "HerschelBulkley",
  "InitialState",
  "InstantaneousMaterial",
  "KAPPA",
  "LIQUID_EOS",
  "LinearMaxwell",
  "LinearPTT",
  "MaterialModel",
  "ModifiedPowellEyring",
  "MooneyRivlin",
  "NEEDS_EOS",
  "NeoHookean",
  "NeoHookeanKelvinVoigt",
  "Newtonian",
  "NoStress",
  "OPERATORS",
  "Ogden",
  "OldroydB",
  "P8",
  "PhysicalParameters",
  "PowellEyring",
  "PowerLaw",
  "PreparedProblem",
  "QuadraticKelvinVoigt",
  "QuadraticZener",
  "RHO",
  "SURF",
  "SampledForcing",
  "SimulationConfig",
  "SimulationError",
  "SimulationResult",
  "SolverStats",
  "SweepResult",
  "TwoModeQuadraticZener",
  "ViscousModel",
  "Yeoh",
  "Zener",
  "__version__",
  "dynamics_code",
  "operator_name",
  "prepare",
  "simulate",
  "simulate_with_sensitivities",
]

from ._config import (  # noqa: F401
  C8,
  CollapseInitialization,
  CollapseStats,
  DYNAMICS,
  InitialState,
  KAPPA,
  LIQUID_EOS,
  MediumOperators,
  NEEDS_EOS,
  OPERATORS,
  P8,
  PhysicalParameters,
  PreparedDistributedStress,
  PreparedForcing,
  PreparedInstantaneousMaterial,
  RHO,
  SURF,
  SampledForcing,
  SimulationConfig,
  SimulationError,
  SimulationResult,
  SolverStats,
  StateLayout,
  SweepResult,
  _CP,
  _D0,
  _KM,
  _LHEAT,
  _LT,
  _MWG,
  _MWV,
  _RU,
  _freeze_array,
  _readonly_optional,
  _validate_inputs,
  dynamics_code,
  operator_name,
)

from ._thermal import (  # noqa: F401
  _GAM_TAIT,
  _HUGONIOT_S,
  _NOG,
  _NSTATE_TAIT,
  _apply_thermal_boundaries,
  _dissipation,
  _distributed_dissipation,
  _instantaneous_dissipation,
  _kv_of_T,
  _mie_F,
  _mie_gruneisen,
  _mu_of_A,
  _T_of_kv,
  _bracketed_root,
  _wall_theta_bw,
  _wall_theta_bw_full,
  pvsat,
)


from ._materials import (  # noqa: F401
  _is_distributed_stress,
  _stress_state_count,
  ArrudaBoyce,
  Bingham,
  CarreauYasuda,
  CarreauZener,
  Cross,
  ElasticModel,
  Fung,
  Gent,
  Giesekus,
  HerschelBulkley,
  InstantaneousMaterial,
  LinearPTT,
  MaterialModel,
  ModifiedPowellEyring,
  MooneyRivlin,
  NeoHookean,
  NeoHookeanKelvinVoigt,
  Ogden,
  Newtonian,
  NoStress,
  OldroydB,
  PowellEyring,
  PowerLaw,
  QuadraticKelvinVoigt,
  QuadraticZener,
  TwoModeQuadraticZener,
  ViscousModel,
  Yeoh,
  LinearMaxwell,
  Zener,
  _finite_nonnegative,
  _finite_positive,
)

from ._stress import (  # noqa: F401
  _MaterialDomainError,
  _PE_SERIES_LIMIT,
  _distributed_stress,
  _distributed_stress_integral,
  _elastic_integrand,
  _instantaneous_stress,
  _powell_eyring_terms,
  _stress,
  _viscosity_and_tangent,
)

from ._prepare import (  # noqa: F401
  _collapse_memory_state,
  _collapse_zener_rhs,
  _material_scales,
  _prepare_distributed_stress,
  _prepare_forcing,
  _prepare_instantaneous_material,
  _thermal_state,
  params,
)

from ._rhs import (  # noqa: F401
  _pinf,
  _rhs,
  _rhs_args,
  _sampled_pressure,
)

from ._solver import (  # noqa: F401
  PreparedProblem,
  prepare,
  _build_result,
  _integrate_prepared,
  _solve_prepared,
  _thermal_outputs,
  _validate_state,
  simulate,
  simulate_with_sensitivities,
)
